image: ghcr.io/cirruslabs/android-sdk:34

options:
  size: 2x   # faster build

pipelines:
  branches:
    develop:
      - step:
          name: Build Debug
          caches:
            - gradle
          script:
            - chmod +x gradlew
            - ./gradlew clean assembleDebug
          artifacts:
            - app/build/outputs/**

    main:
      - step:
          name: Build Signed Release AAB
          caches:
            - gradle
          script:
            # Decode keystore
            - echo $ANDROID_KEYSTORE | base64 --decode > keystore.jks

            # Clean & Build
            - chmod +x gradlew
            - ./gradlew clean bundleRelease

          artifacts:
            - app/build/outputs/bundle/release/app-release.aab

      - step:
          name: Upload to Play Store
          image: fastlane/fastlane:latest
          script:
            # Write service account JSON
            - echo $GOOGLE_PLAY_JSON > play-store.json

            # Install supply (if needed)
            - gem install fastlane -NV

            # Upload AAB
            - fastlane supply \
                --aab app/build/outputs/bundle/release/app-release.aab \
                --json_key play-store.json \
                --package_name $PACKAGE_NAME \
                --track $PLAY_TRACK \
                --skip_upload_metadata true \
                --skip_upload_images true \
                --skip_upload_screenshots true